"""
Generate worldLocations.json — 20 globally famous landmarks with
HIGH-CONFIDENCE walkable Google Street View coverage at the site.

Replaces src/data/indiaLocations.json (filename kept for compatibility).
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_FRONTEND = ROOT / "src" / "data" / "indiaLocations.json"
OUT_AI       = ROOT / "ai_engine" / "data" / "indiaLocations.json"

# ── Feature-vector preset helpers ─────────────────────────────────────────
def fv(historical=0, architectural=0, religious=0, natural=0, cultural=0,
       artistic=0, educational=0, adventurous=0, ancient=0, medieval=0,
       colonial=0, modern=0):
    return {
        "historical":    historical,
        "architectural": architectural,
        "religious":     religious,
        "natural":       natural,
        "cultural":      cultural,
        "artistic":      artistic,
        "educational":   educational,
        "adventurous":   adventurous,
        "ancient":       ancient,
        "medieval":      medieval,
        "colonial":      colonial,
        "modern":        modern,
    }


def node(id_, label, panorama, fallback, connected=None, hotspots=None, wiki=None):
    return {
        "id":               id_,
        "label":            label,
        "panoramaUrl":      panorama,
        "fallbackImageUrl": fallback,
        "connectedNodes":   connected or [],
        "hotspots":         hotspots or [],
        **({"wikiContext": wiki} if wiki else {}),
    }


def hs(id_, kind, az, el, label, content=None, target=None):
    h = {"id": id_, "type": kind, "azimuth": az, "elevation": el, "label": label}
    if content is not None:
        h["content"] = content
    if target is not None:
        h["targetNodeId"] = target
    return h


# Each location follows the exact IndiaLocation schema.
# panoramaUrl uses Unsplash for visual variety on the Pannellum/3D fallback
# (Street View mode uses the keyed Embed API based on lat/lng).
def panorama(keyword):
    return f"https://source.unsplash.com/3840x1920/?{keyword.replace(' ', '+')}"

def fallback(keyword):
    return f"https://source.unsplash.com/1920x960/?{keyword.replace(' ', '+')}"


LOCATIONS = [
    # ── EUROPE ────────────────────────────────────────────────────────────
    {
        "id":               "eiffel-tower-paris",
        "name":             "Eiffel Tower",
        "city":             "Paris",
        "state":            "France",
        "region":           "europe",
        "category":         "modern",
        "lat":              48.8584, "lng": 2.2945,
        "description":      "The Eiffel Tower is a 330-metre wrought-iron lattice tower designed by Gustave Eiffel for the 1889 World's Fair. Once mocked by Parisian artists, it is now the most-visited paid monument on Earth and France's defining symbol.",
        "established":      "1889",
        "unescoStatus":     True,
        "bestSeason":       ["April", "May", "September", "October"],
        "tags":             ["paris", "iron", "tower", "world-icon", "engineering", "panorama"],
        "wikiSlug":         "Eiffel_Tower",
        "wikimediaCategory":"Eiffel Tower",
        "features":         fv(historical=0.9, architectural=1.0, cultural=1.0, artistic=0.85, educational=0.9, modern=0.9, colonial=0.6),
        "nodes": [
            node("ef-base", "Champ de Mars (Base)",
                 panorama("eiffel tower base paris"), fallback("eiffel tower paris"),
                 connected=["ef-trocadero"],
                 hotspots=[hs("ef-1","navigation",30,0,"Cross to Trocadéro", target="ef-trocadero"),
                           hs("ef-2","info",120,15,"Iron Lattice","Made of 18,038 puddle-iron pieces joined by 2.5 million rivets — a marvel of late-19th-century engineering.")]),
            node("ef-trocadero", "Trocadéro Gardens",
                 panorama("trocadero paris view"), fallback("trocadero paris"),
                 connected=["ef-base"],
                 hotspots=[hs("ef-3","navigation",210,0,"Walk back to base", target="ef-base")]),
        ],
    },
    {
        "id":               "colosseum-rome",
        "name":             "Colosseum",
        "city":             "Rome",
        "state":            "Italy",
        "region":           "europe",
        "category":         "heritage",
        "lat":              41.8902, "lng": 12.4922,
        "description":      "The Colosseum is the largest ancient amphitheatre ever built, completed under Emperor Titus in 80 CE. It once seated up to 80,000 spectators for gladiatorial contests, mock sea battles, and public spectacles.",
        "established":      "80 CE",
        "unescoStatus":     True,
        "bestSeason":       ["April", "May", "September", "October"],
        "tags":             ["rome", "roman", "amphitheatre", "gladiators", "ancient", "wonder"],
        "wikiSlug":         "Colosseum",
        "wikimediaCategory":"Colosseum",
        "features":         fv(historical=1.0, architectural=1.0, cultural=1.0, artistic=0.8, educational=1.0, adventurous=0.3, ancient=1.0),
        "nodes": [
            node("col-arena","Arena Floor", panorama("colosseum interior"), fallback("colosseum rome"),
                 hotspots=[hs("col-1","info",90,10,"Hypogeum","Beneath the arena floor lay a two-level subterranean network of tunnels, animal cages, and lifts that delivered combatants up through trapdoors.")]),
        ],
    },
    {
        "id":               "leaning-tower-pisa",
        "name":             "Leaning Tower of Pisa",
        "city":             "Pisa",
        "state":            "Italy",
        "region":           "europe",
        "category":         "heritage",
        "lat":              43.7230, "lng": 10.3966,
        "description":      "The Leaning Tower is the freestanding bell tower of Pisa Cathedral, famous for its near-four-degree tilt caused by an unstable foundation laid in 1173. Stabilisation work between 1990 and 2001 corrected its lean by half a degree.",
        "established":      "1372",
        "unescoStatus":     True,
        "bestSeason":       ["April", "May", "September", "October"],
        "tags":             ["pisa", "tower", "medieval", "marble", "miracle"],
        "wikiSlug":         "Leaning_Tower_of_Pisa",
        "wikimediaCategory":"Leaning Tower of Pisa",
        "features":         fv(historical=0.9, architectural=1.0, religious=0.4, cultural=0.85, artistic=0.7, educational=0.85, medieval=1.0),
        "nodes": [node("pisa-square","Piazza dei Miracoli", panorama("leaning tower pisa"), fallback("pisa italy"), hotspots=[])],
    },
    {
        "id":               "sagrada-familia-barcelona",
        "name":             "Sagrada Família",
        "city":             "Barcelona",
        "state":            "Spain",
        "region":           "europe",
        "category":         "spiritual",
        "lat":              41.4036, "lng": 2.1744,
        "description":      "Antoni Gaudí's unfinished basilica is a UNESCO World Heritage Site begun in 1882 and still under construction. Its forest-like nave and twisting towers fuse Gothic, Art Nouveau, and biological forms into a singular Catalan masterpiece.",
        "established":      "1882 (ongoing)",
        "unescoStatus":     True,
        "bestSeason":       ["March", "April", "October", "November"],
        "tags":             ["gaudi", "barcelona", "basilica", "modernisme", "art-nouveau", "spires"],
        "wikiSlug":         "Sagrada_Família",
        "wikimediaCategory":"Sagrada Família",
        "features":         fv(architectural=1.0, religious=0.9, cultural=0.95, artistic=1.0, educational=0.85, modern=0.8, colonial=0.2),
        "nodes": [node("sf-front","Nativity Façade", panorama("sagrada familia"), fallback("barcelona"), hotspots=[])],
    },
    {
        "id":               "big-ben-london",
        "name":             "Big Ben & Westminster",
        "city":             "London",
        "state":            "United Kingdom",
        "region":           "europe",
        "category":         "heritage",
        "lat":              51.4994, "lng": -0.1245,
        "description":      "The Elizabeth Tower — popularly Big Ben — houses the Great Bell of Westminster, completed in 1859. Together with the Palace of Westminster it forms the seat of British government and a UNESCO World Heritage Site since 1987.",
        "established":      "1859",
        "unescoStatus":     True,
        "bestSeason":       ["May", "June", "July", "September"],
        "tags":             ["london", "clock", "westminster", "parliament", "victorian"],
        "wikiSlug":         "Big_Ben",
        "wikimediaCategory":"Elizabeth Tower",
        "features":         fv(historical=0.95, architectural=1.0, cultural=1.0, artistic=0.7, educational=0.9, colonial=0.85, modern=0.5),
        "nodes": [node("bb-bridge","Westminster Bridge", panorama("big ben london"), fallback("london"), hotspots=[])],
    },
    {
        "id":               "tower-bridge-london",
        "name":             "Tower Bridge",
        "city":             "London",
        "state":            "United Kingdom",
        "region":           "europe",
        "category":         "modern",
        "lat":              51.5055, "lng": -0.0754,
        "description":      "Tower Bridge is a combined bascule and suspension bridge over the Thames, completed in 1894. Its Gothic Revival towers and twin lifting roadways have become an enduring icon of Victorian engineering.",
        "established":      "1894",
        "unescoStatus":     False,
        "bestSeason":       ["May", "June", "July", "September"],
        "tags":             ["london", "thames", "bascule", "victorian", "engineering"],
        "wikiSlug":         "Tower_Bridge",
        "wikimediaCategory":"Tower Bridge",
        "features":         fv(historical=0.85, architectural=1.0, cultural=0.85, artistic=0.6, educational=0.8, modern=0.7, colonial=0.85),
        "nodes": [node("tb-deck","Bridge Deck", panorama("tower bridge london"), fallback("london"), hotspots=[])],
    },
    {
        "id":               "stonehenge-uk",
        "name":             "Stonehenge",
        "city":             "Wiltshire",
        "state":            "United Kingdom",
        "region":           "europe",
        "category":         "heritage",
        "lat":              51.1789, "lng": -1.8262,
        "description":      "Stonehenge is a prehistoric stone circle built in stages between 3000 and 2000 BCE on Salisbury Plain. Its alignment with the solstices and the origin of its bluestones from Wales remain partly unexplained.",
        "established":      "~3000 BCE",
        "unescoStatus":     True,
        "bestSeason":       ["May", "June", "July"],
        "tags":             ["neolithic", "megalith", "salisbury", "solstice", "mystery"],
        "wikiSlug":         "Stonehenge",
        "wikimediaCategory":"Stonehenge",
        "features":         fv(historical=1.0, architectural=0.85, religious=0.6, natural=0.4, cultural=0.95, educational=1.0, adventurous=0.4, ancient=1.0),
        "nodes": [node("sh-ring","Sarsen Ring", panorama("stonehenge"), fallback("stonehenge england"), hotspots=[])],
    },
    {
        "id":               "brandenburg-gate-berlin",
        "name":             "Brandenburg Gate",
        "city":             "Berlin",
        "state":            "Germany",
        "region":           "europe",
        "category":         "heritage",
        "lat":              52.5163, "lng": 13.3777,
        "description":      "The Brandenburg Gate is an 18th-century neoclassical triumphal arch crowned by the Quadriga statue. From the Cold War division of the city to reunification celebrations in 1989, it has stood as Germany's defining political monument.",
        "established":      "1791",
        "unescoStatus":     False,
        "bestSeason":       ["May", "June", "September", "October"],
        "tags":             ["berlin", "neoclassical", "triumphal-arch", "reunification", "history"],
        "wikiSlug":         "Brandenburg_Gate",
        "wikimediaCategory":"Brandenburg Gate",
        "features":         fv(historical=1.0, architectural=0.95, cultural=1.0, artistic=0.8, educational=0.95, colonial=0.7, modern=0.6),
        "nodes": [node("bg-pariser","Pariser Platz", panorama("brandenburg gate berlin"), fallback("berlin"), hotspots=[])],
    },
    {
        "id":               "acropolis-athens",
        "name":             "Acropolis of Athens",
        "city":             "Athens",
        "state":            "Greece",
        "region":           "europe",
        "category":         "heritage",
        "lat":              37.9715, "lng": 23.7257,
        "description":      "The Acropolis is the rocky citadel above Athens crowned by the 5th-century BCE Parthenon — the defining monument of Classical Greek architecture and the symbolic birthplace of Western civilization.",
        "established":      "447 BCE",
        "unescoStatus":     True,
        "bestSeason":       ["April", "May", "October"],
        "tags":             ["athens", "parthenon", "classical", "greek", "philosophy"],
        "wikiSlug":         "Acropolis_of_Athens",
        "wikimediaCategory":"Acropolis of Athens",
        "features":         fv(historical=1.0, architectural=1.0, religious=0.7, cultural=1.0, artistic=0.95, educational=1.0, ancient=1.0),
        "nodes": [node("ac-parth","Parthenon", panorama("parthenon acropolis"), fallback("athens greece"), hotspots=[])],
    },
    {
        "id":               "trevi-fountain-rome",
        "name":             "Trevi Fountain",
        "city":             "Rome",
        "state":            "Italy",
        "region":           "europe",
        "category":         "heritage",
        "lat":              41.9009, "lng": 12.4833,
        "description":      "Completed in 1762, the Trevi Fountain is the largest Baroque fountain in Rome — a 26-metre-wide Travertine cascade designed by Nicola Salvi at the terminus of the ancient Aqua Virgo aqueduct.",
        "established":      "1762",
        "unescoStatus":     False,
        "bestSeason":       ["April", "May", "September", "October"],
        "tags":             ["rome", "baroque", "fountain", "salvi", "travertine"],
        "wikiSlug":         "Trevi_Fountain",
        "wikimediaCategory":"Trevi Fountain",
        "features":         fv(historical=0.9, architectural=1.0, cultural=0.95, artistic=1.0, educational=0.85, colonial=0.5),
        "nodes": [node("tf-front","Fountain Plaza", panorama("trevi fountain rome"), fallback("rome italy"), hotspots=[])],
    },

    # ── NORTH AMERICA ─────────────────────────────────────────────────────
    {
        "id":               "statue-of-liberty-nyc",
        "name":             "Statue of Liberty",
        "city":             "New York",
        "state":            "United States",
        "region":           "north-america",
        "category":         "heritage",
        "lat":              40.6892, "lng": -74.0445,
        "description":      "Liberty Enlightening the World, a gift from France in 1886, stands 93 metres tall on Liberty Island in New York Harbour. The neoclassical copper figure has welcomed ships into America for nearly 140 years.",
        "established":      "1886",
        "unescoStatus":     True,
        "bestSeason":       ["May", "June", "September", "October"],
        "tags":             ["new-york", "liberty-island", "neoclassical", "copper", "immigration"],
        "wikiSlug":         "Statue_of_Liberty",
        "wikimediaCategory":"Statue of Liberty",
        "features":         fv(historical=0.95, architectural=0.9, cultural=1.0, artistic=0.85, educational=0.95, colonial=0.7, modern=0.5),
        "nodes": [node("sol-base","Pedestal Plaza", panorama("statue of liberty"), fallback("new york"), hotspots=[])],
    },
    {
        "id":               "times-square-nyc",
        "name":             "Times Square",
        "city":             "New York",
        "state":            "United States",
        "region":           "north-america",
        "category":         "modern",
        "lat":              40.7580, "lng": -73.9855,
        "description":      "Times Square is the bow-tie-shaped intersection at Broadway and 7th Avenue in Midtown Manhattan, defined by its illuminated billboards and 24-hour neon glow. It hosts the iconic New Year's Eve ball drop watched by a billion people worldwide.",
        "established":      "1904",
        "unescoStatus":     False,
        "bestSeason":       ["May", "June", "September", "October"],
        "tags":             ["new-york", "broadway", "neon", "billboards", "manhattan"],
        "wikiSlug":         "Times_Square",
        "wikimediaCategory":"Times Square",
        "features":         fv(historical=0.5, cultural=1.0, artistic=0.7, educational=0.4, modern=1.0),
        "nodes": [node("ts-crossroads","The Crossroads", panorama("times square new york"), fallback("new york"), hotspots=[])],
    },
    {
        "id":               "central-park-nyc",
        "name":             "Central Park",
        "city":             "New York",
        "state":            "United States",
        "region":           "north-america",
        "category":         "nature",
        "lat":              40.7829, "lng": -73.9654,
        "description":      "Central Park is an 843-acre urban park in Manhattan designed by Frederick Law Olmsted and Calvert Vaux in 1858. Its meadows, lakes, woods, and the Bethesda Terrace form one of the most visited urban parks on Earth.",
        "established":      "1858",
        "unescoStatus":     False,
        "bestSeason":       ["April", "May", "October", "November"],
        "tags":             ["new-york", "manhattan", "olmsted", "park", "lake"],
        "wikiSlug":         "Central_Park",
        "wikimediaCategory":"Central Park",
        "features":         fv(historical=0.7, natural=1.0, cultural=0.9, artistic=0.7, educational=0.8, adventurous=0.5, modern=0.7),
        "nodes": [node("cp-bethesda","Bethesda Terrace", panorama("central park bethesda"), fallback("central park new york"), hotspots=[])],
    },
    {
        "id":               "brooklyn-bridge-nyc",
        "name":             "Brooklyn Bridge",
        "city":             "New York",
        "state":            "United States",
        "region":           "north-america",
        "category":         "modern",
        "lat":              40.7061, "lng": -73.9969,
        "description":      "Completed in 1883, the Brooklyn Bridge was the world's first steel-wire suspension bridge and the longest at the time. It still carries pedestrians, cyclists, and traffic between Manhattan and Brooklyn across the East River.",
        "established":      "1883",
        "unescoStatus":     False,
        "bestSeason":       ["April", "May", "September", "October"],
        "tags":             ["new-york", "brooklyn", "suspension", "east-river", "engineering"],
        "wikiSlug":         "Brooklyn_Bridge",
        "wikimediaCategory":"Brooklyn Bridge",
        "features":         fv(historical=0.85, architectural=1.0, cultural=0.9, artistic=0.6, educational=0.85, colonial=0.6, modern=0.9),
        "nodes": [node("bb-deck","Pedestrian Promenade", panorama("brooklyn bridge"), fallback("new york"), hotspots=[])],
    },
    {
        "id":               "golden-gate-bridge-sf",
        "name":             "Golden Gate Bridge",
        "city":             "San Francisco",
        "state":            "United States",
        "region":           "north-america",
        "category":         "modern",
        "lat":              37.8199, "lng": -122.4783,
        "description":      "The Golden Gate Bridge is a 2.7-kilometre Art Deco suspension bridge linking San Francisco to Marin County. When it opened in 1937 it was the longest and tallest suspension bridge in the world; its distinctive International Orange paint is now an icon of California.",
        "established":      "1937",
        "unescoStatus":     False,
        "bestSeason":       ["May", "June", "September", "October"],
        "tags":             ["san-francisco", "suspension", "art-deco", "california", "pacific"],
        "wikiSlug":         "Golden_Gate_Bridge",
        "wikimediaCategory":"Golden Gate Bridge",
        "features":         fv(historical=0.7, architectural=1.0, cultural=0.85, artistic=0.7, educational=0.8, modern=1.0),
        "nodes": [node("gg-vista","Vista Point", panorama("golden gate bridge"), fallback("san francisco"), hotspots=[])],
    },

    # ── ASIA / OCEANIA ────────────────────────────────────────────────────
    {
        "id":               "taj-mahal-agra",
        "name":             "Taj Mahal",
        "city":             "Agra",
        "state":            "India",
        "region":           "asia",
        "category":         "heritage",
        "lat":              27.1751, "lng": 78.0421,
        "description":      "The Taj Mahal is an ivory-white marble mausoleum built by Mughal emperor Shah Jahan in memory of his wife Mumtaz Mahal. Completed in 1643 CE, it is one of the seven wonders of the modern world.",
        "established":      "1643 CE",
        "unescoStatus":     True,
        "bestSeason":       ["October", "November", "December", "February"],
        "tags":             ["mughal", "marble", "mausoleum", "world-wonder", "symmetry"],
        "wikiSlug":         "Taj_Mahal",
        "wikimediaCategory":"Taj Mahal",
        "features":         fv(historical=0.95, architectural=1.0, religious=0.5, cultural=0.95, artistic=1.0, educational=0.9, medieval=1.0),
        "nodes": [node("tj-gate","Great Gate (Darwaza)", panorama("taj mahal"), fallback("taj mahal agra"), hotspots=[])],
    },
    {
        "id":               "tokyo-tower",
        "name":             "Tokyo Tower",
        "city":             "Tokyo",
        "state":            "Japan",
        "region":           "asia",
        "category":         "modern",
        "lat":              35.6586, "lng": 139.7454,
        "description":      "Tokyo Tower is a 333-metre red and white communications and observation tower in the Minato ward, modelled on the Eiffel Tower but taller. Completed in 1958, it became the symbol of post-war Japan's recovery and modernity.",
        "established":      "1958",
        "unescoStatus":     False,
        "bestSeason":       ["March", "April", "October", "November"],
        "tags":             ["tokyo", "minato", "communications", "observation", "post-war"],
        "wikiSlug":         "Tokyo_Tower",
        "wikimediaCategory":"Tokyo Tower",
        "features":         fv(architectural=0.9, cultural=0.9, educational=0.7, modern=1.0),
        "nodes": [node("tt-base","Shiba Park", panorama("tokyo tower"), fallback("tokyo"), hotspots=[])],
    },
    {
        "id":               "shibuya-crossing-tokyo",
        "name":             "Shibuya Crossing",
        "city":             "Tokyo",
        "state":            "Japan",
        "region":           "asia",
        "category":         "modern",
        "lat":              35.6595, "lng": 139.7005,
        "description":      "Shibuya Scramble Crossing is the busiest pedestrian intersection in the world, where up to 3,000 people stream across in every signal cycle. Surrounded by jumbo screens and neon façades, it is the defining image of contemporary Tokyo.",
        "established":      "1973",
        "unescoStatus":     False,
        "bestSeason":       ["March", "April", "October", "November"],
        "tags":             ["tokyo", "shibuya", "scramble", "pedestrian", "neon"],
        "wikiSlug":         "Shibuya_Crossing",
        "wikimediaCategory":"Shibuya Crossing",
        "features":         fv(cultural=1.0, educational=0.5, modern=1.0),
        "nodes": [node("sb-scramble","The Scramble", panorama("shibuya crossing tokyo"), fallback("tokyo japan"), hotspots=[])],
    },
    {
        "id":               "sydney-opera-house",
        "name":             "Sydney Opera House",
        "city":             "Sydney",
        "state":            "Australia",
        "region":           "oceania",
        "category":         "modern",
        "lat":              -33.8568, "lng": 151.2153,
        "description":      "The Sydney Opera House is a multi-venue performing arts centre with a series of precast concrete shells that sweep above Sydney Harbour. Designed by Jørn Utzon and completed in 1973, it is a 20th-century architectural masterpiece and a UNESCO World Heritage Site.",
        "established":      "1973",
        "unescoStatus":     True,
        "bestSeason":       ["September", "October", "March", "April"],
        "tags":             ["sydney", "harbour", "utzon", "concrete", "opera", "expressionism"],
        "wikiSlug":         "Sydney_Opera_House",
        "wikimediaCategory":"Sydney Opera House",
        "features":         fv(architectural=1.0, cultural=1.0, artistic=1.0, educational=0.85, modern=1.0),
        "nodes": [node("so-forecourt","Forecourt", panorama("sydney opera house"), fallback("sydney"), hotspots=[])],
    },

    # ── SOUTH AMERICA ─────────────────────────────────────────────────────
    {
        "id":               "christ-the-redeemer-rio",
        "name":             "Christ the Redeemer",
        "city":             "Rio de Janeiro",
        "state":            "Brazil",
        "region":           "south-america",
        "category":         "spiritual",
        "lat":              -22.9519, "lng": -43.2105,
        "description":      "Christ the Redeemer is a 38-metre Art Deco statue of Jesus Christ atop Mount Corcovado, completed in 1931. It overlooks Rio de Janeiro with arms outstretched 28 metres wide and is one of the seven New Wonders of the World.",
        "established":      "1931",
        "unescoStatus":     False,
        "bestSeason":       ["May", "June", "July", "August", "September"],
        "tags":             ["rio", "corcovado", "art-deco", "statue", "new-wonder"],
        "wikiSlug":         "Christ_the_Redeemer_(statue)",
        "wikimediaCategory":"Christ the Redeemer",
        "features":         fv(architectural=0.85, religious=1.0, cultural=1.0, artistic=0.85, educational=0.8, modern=0.85),
        "nodes": [node("cr-base","Statue Plaza", panorama("christ the redeemer rio"), fallback("rio de janeiro"), hotspots=[])],
    },
]


def main() -> None:
    serialised = json.dumps(LOCATIONS, indent=2, ensure_ascii=False)
    OUT_FRONTEND.write_text(serialised, encoding="utf-8")
    OUT_AI.write_text(serialised, encoding="utf-8")
    print(f"Wrote {len(LOCATIONS)} world locations:")
    print(f"  - {OUT_FRONTEND.relative_to(ROOT)}")
    print(f"  - {OUT_AI.relative_to(ROOT)}")
    for loc in LOCATIONS:
        print(f"  · {loc['id']:<35} {loc['name']:<30} ({loc['city']}, {loc['state']})")


if __name__ == "__main__":
    main()
